config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }

  devise_scope :user do
    authenticated :user, lambda {|u| u.type == "Buyer" || "Seller"} do
      root 'products#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  concern :attachable do
    resources :attachments, only: :create
  end
  
  resources :products, concerns: [:attachable] do
    member do 
     post 'approve'
     post :disapprove
    end
    collection do
      get :seller_product
    end
  end
  resources :users, only: %i[index show]
  resources :carts, only: %i[index] do 
    member do 
      post :add_to
    end
  end
  
  resources :favourites, only: %i[index] do 
    member do 
      post :add_to
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products

  def admin?
    type == 'Admin'
  end

  def buyer?
    type == 'Buyer'
  end

  def seller?
    type == 'Seller'
  end

end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  def update
    if some_condition
      redirect_to root_path
    else
      super
    end
  end

  private

    # this is called when creating invitation
    # should return an instance of resource class
    def invite_resource
      # skip sending emails on invite
      super { |user| user.skip_invitation = true }
    end

    # this is called when accepting invitation
    # should return an instance of resource class
    def accept_resource
      resource = resource_class.accept_invitation!(update_resource_params)
      # Report accepting invitation to analytics
      Analytics.report('invite.accept', resource.id)
      resource
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  def create
    params[:user] = params[:user]&.merge(type: params[:user][:type].capitalize)
    super
  end

  def update
    params[:user] = params[:user]&.merge(type: params[:user][:type].capitalize)
    super
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[type])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[type])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show]
    before_action :check_authorization
    def index
        @sellers = Seller.all
        @buyers = Buyer.all
    end

    def show
        @products = @user.products
    end
private
    def find_user
        @user = User.find(params[:id])
    end

    def check_authorization
        redirect_to products_path unless current_user.admin?
    end

end

app/views/users/index.html.erb
<h4>Sellers</h4>
<%@sellers&.each do |user|%>
    <a href="<%=user_path(user.id)%>"><%= user.email%></a>
<%end%>

<h4>Buyers</h4>
<%@buyers&.each do |user|%>
    <a href="<%=user_path(user.id)%>"><%= user.email%></a>
<%end%>

app/views/users/show.html.erb
<table class="table admin-table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Sku</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%@products&.each do |product|%>
        <tr>
        <td><%= product.name%></td>
        <td><%= product.sku%></td>
        <td><%= product.status%></td>
        <td> <a href="<%= product_path(product.id)%>" target="_blank">View</a>
        <%= link_to "Approve", approve_product_path(product.id), :method => :post %>
        <%= link_to "Disapprove", disapprove_product_path(product.id), :method => :post %><td>
        </tr>
    <%end%>

  </tbody>
</table>