config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }

  devise_scope :user do
    authenticated :user, lambda {|u| u.type == "Buyer" || "Seller"} do
      root 'products#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  concern :attachable do
    resources :attachments, only: :create
  end
  
  resources :products, concerns: [:attachable] do
    member do 
     post 'approve'
     post :disapprove
    end
    collection do
      get :seller_product
    end
  end
  resources :users, only: %i[index show]
  resources :carts, only: %i[index] do 
    member do 
      post :add_to
    end
  end
  
  resources :favourites, only: %i[index] do 
    member do 
      post :add_to
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :carts
    has_many :buyers, through: :carts
    
    has_many :favourites
    has_many :buyers, through: :favourites

    has_many :attachments, as: :attached_item, dependent: :destroy
    accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: proc { |attributes| attributes[:attachment].nil? }
    
    scope :approve, -> { where(status: "approve") }
    scope :disapprove, -> { where(status: "disapprove") }
    validates_presence_of :name
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, except: [:index, :new, :seller_product, :create]
    def index
        @products = Product.all.approve
    end

    def seller_product
        @products = current_user.products
        render 'index'
    end

    def show
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        @product.user = current_user
        if @product.save
            redirect_to @product
        else
            render json: { errors: @product.errors.full_messages }, status: 422
        end 
    end

    def edit
    end

    def update
        @product.update_attributes(product_params)
        @product.status = "pending"
        if @product.save
            redirect_to @product
        else
            render json: { errors: @product.errors.full_messages }, status: 422
        end
    end

    def approve
        @product.update_attribute(:status, 'approve')
        redirect_back fallback_location: products_path
    end

    def disapprove
        @product.update_attribute(:status, 'disapprove')
        redirect_back fallback_location: products_path
    end

    private
    def product_params
        params.require(:product).permit(:name,:sku,attachments_attributes: [:id, :attachment, :attachment_cache, :_destroy])

    end

    def find_product
        @product = Product.find(params[:id])
    end
end

app/views/products/edit.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <h2>Update Product</h2>
    </div>
    <%= nested_form_for @product,html: { multipart: true }, local: true do |f| %>
      <%= f.text_field :name, placeholder: "name" ,class: "fadeIn second"%>
      <%= f.text_field :sku, placeholder: "sku", class: "fadeIn third" %>

      <p><%= f.link_to_add "Add an attachment", :attachments %></p>
      
      <%= f.fields_for :attachments do |attachment_form| %>
        <%= attachment_form.file_field :attachment %>
        <%= attachment_form.hidden_field :attachment_cache %>
        <%= attachment_form.link_to_remove "Remove this attachment" %>
      <% end %>
        <div class="fadeIn fourth">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<%if current_user.seller? %>
    <a href="<%= new_product_path%>">Add new product</a>
<%elsif current_user.buyer? %>
    <%= link_to "Cart |", carts_path, local: true, :method => :get %>
    <%= link_to "Favourites", favourites_path, local: true, :method => :get %>
  <%elsif current_user.admin? %>
    <%= link_to "Users", users_path, local: true, :method => :get %>
<%end%>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Sku</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product|%>
        <tr>
            <td><a href="<%= product_path(product.id)%>"><%= product.name%></a></td>
            <td><%= product.sku%></td>
            <td><%= product.status%></td>
        </tr>
    <%end%>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <h2>Add New Product</h2>
    </div>
    <%= nested_form_for @product,html: { multipart: true }, local: true do |f| %>
      <%= f.text_field :name, placeholder: "name" ,class: "fadeIn second"%>
      <%= f.text_field :sku, placeholder: "sku", class: "fadeIn third" %>

      <p><%= f.link_to_add "Add an attachment", :attachments %></p>
      
      <%= f.fields_for :attachments do |attachment_form| %>
        <%= attachment_form.file_field :attachment %>
        <%= attachment_form.hidden_field :attachment_cache %>
        <%= attachment_form.link_to_remove "Remove this attachment" %>
      <% end %>
        <div class="fadeIn fourth">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<%if current_user.seller? %>
    <a href="<%= new_product_path%>">Add new product</a>
    <a href="<%= edit_product_path%>">Edit product</a>
<%elsif current_user.buyer? %>
    <%= link_to "Cart |", carts_path, local: true, :method => :get %>
    <%= link_to "Add to cart |", add_to_cart_path(@product.id), remote: true, :method => :post %>
    
    <%= link_to "Favourites |", favourites_path, local: true, :method => :get %>
    <%= link_to "Add to favourites", add_to_favourite_path(@product.id), remote: true, :method => :post %>
<%end%>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Sku</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>    
        <tr>
            <td><%= @product.name%></td>
            <td><%= @product.sku%></td>
            <td><%= @product.status%></td>
        </tr>    
  </tbody>
</table>

<h5>Attachments</h5>
  <%@product.attachments.each do |attachment|%>
    <%= attachment.original_filename%>
    <%= image_tag(attachment.attachment_url, class: "image-width") %>
<%end%>